#!/bin/bash

echo ""
echo "*****  Préparation Préliminaire  *****"
echo ""


#echo 'Acquire::http::Proxy "http://apt-cache.fab:3142";' > /etc/apt/apt.conf.d/02proxy
#chown root:root /etc/apt/apt.conf.d/02proxy
#chmod 644 /etc/apt/apt.conf.d/02proxy

apt-add-repository ppa:ansible/ansible -y
apt update
apt full-upgrade -y

apt install ansible git -y

echo ""
echo "*****  Provisionnement Initiale  *****"
echo ""

ansible-pull -U https://github.com/fablab-loritz/laptop_playbook.git

echo ""
echo "*****       Provisionnement Terminé       *****"
echo "***** Vous pouvez redémarrer l'ordianteur *****"
echo ""
