---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  

  tasks:
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/loritz-user.yml
    - include_tasks: tasks/bin.yml
    - include_tasks: tasks/cleanup.yml