- name: Suppression dossier utilisateur axel
  file:
    path: /home/axel
    state: absent

- name: Nettoie fstab
  ansible.posix.mount:
    path: /mnt/ECHANGE-INSCRIPTIONS
    state: absent_from_fstab
