- name: Suppression dossier utilisateur axel
  file:
    path: /home/axel
    state: absent

- name: Nettoie fstab
  ansible.posix.mount:
    src: 192.168.8.251:/ECHANGE-INSCRIPTIONS
    path: /mnt/ECHANGE-INSCRIPTIONS
    state: absent_from_fstab
    fstype: nfs