- name: create ansible user
  user:
    name: ansible
    system: yes

- name: Create sudoers file for ansible
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansible
    content: |
      ansible ALL=(ALL) NOPASSWD:ALL
    owner: root
    group: root
    mode: '0440'